### ISSUE TITLE
Disable logs in LogCat

### ISSUE THREAD

**Issue by sudansh** [SiftScience/sift-android#101]
How can I disable the logs to show on the logcat?

**Comment by vincent-sift** [comment]
Hello @sudansh your issue title and description are misleading. What are you trying to do?

**Comment by sudansh** [comment]
> Hello @sudansh your issue title and description are misleading. What are you trying to do?

Hi,
On debug `buildType` of my app. I get the SIFT logs. Is there a way to disable them to show on Android Studio LogCat

**Comment by vincent-sift** [comment]
My understanding is that because we are using `android.util.Log` in the `sift-android` sdk that you should see those logs in LogCat. As you can see from this article: https://stackoverflow.com/questions/2364811/how-do-i-write-outputs-to-the-log-in-android. What behavior are you seeing in your app?

If you wanted to disable the logging outright you could set this property to off
```
android.util.Log = OFF
```
Or you can turn off specific tags that you don't want to be displayed. This article may be helpful as well: https://stackoverflow.com/questions/2018263/how-do-i-enable-disable-log-levels-in-android
