### ISSUE TITLE
Sift.unsetUserId() and Sift.setUserId() are unsafe if used outside of the Activity lifecycle

### ISSUE THREAD

**Issue by edenman** [SiftScience/sift-android#50]
I initialize Sift as recommended, in the Activity.  I recently upgraded from 0.9.7 to 0.10.0-beta and now code that happens outside the activity lifecycle can't safely call unsetUserId/setUserId (instance is null, so my app crashes).  Is there some way I can check to see if Sift has been initialized?  Or can you guys make those calls safe?

**Comment by quanpod** [comment]
@edenman are you on the very latest?  @garylee1 should have a fix that in 0.10.1-beta

**Comment by edenman** [comment]
0.10.1-beta still seems to have this:
```
    public static void setUserId(String userId) {
        instance.setUserId(userId);
    }

    public static void unsetUserId() {
        instance.setUserId(null);
    }
```

**Comment by edenman** [comment]
If I haven't called `Sift.open` yet, `instance` will be null and this call will crash

**Comment by garylee1** [comment]
@edenman We can safeguard against this but you'll still need to call `Sift.open` before setting or unsetting the `userId`. Otherwise, it'll be a no-op or an illegal state exception at best. We've modified our SDK to never release the instance once it's opened, so you provided you've `open`ed, you shouldn't have to worry about the instance being nulled out even outside of the Activity lifecycle.

**Comment by edenman** [comment]
Two options:
1. in the case of "not yet called open", no-op
2. exposing a "isInitialized"/"isOpened" method

I don't have a strong preference between the two.

**Comment by garylee1** [comment]
Sounds good – it'll probably be 1) but i'll keep you looped in.

**Comment by garylee1** [comment]
@edenman I feel like you'd want to know about it though, right? If we don't crash, effectively it's an integration error that will go unnoticed.

**Comment by garylee1** [comment]
*or throw an illegal state exception

**Comment by garylee1** [comment]
I see – that's an interesting idea. We could definitely write it to archive opportunistically such that it's independent of the Sift instance existing. We'll definitely consider that for a future SDK release.

**Comment by falcon4ever** [comment]
@garylee1 +1 on edenman's comment.

Would like to have some way of knowing if Sift has been initialized properly and that **instance** isn't null. Had the app crash because of calling setUserId ()/unsetUserId() without Sift being properly initialized. 

Not entirely sure why but my best guess is that the app is resumed after being killed in the background by the OS. It then probably resumes the activity without initializing Sift.

Before the 0.10.x series, I could use this to prevent an app crash:
if (Sift.get() == null) {
    // Reinitialize if needed
    return;
}

I hope you will consider a fix in the next release that allow us to check it (OR do an instance == null check yourself in those 2 methods). I haven't published my app build with the v0.10.1-beta (as you notified me in the other bug report thread) yet but Sift science is unfortunately the number one cause (30+) of my app crashes according to Fabric Crashlytics.

**Comment by garylee1** [comment]
Sounds good – I'll try to do a release early next week that allows for setting and unsetting the userId in memory regardless of the Sift open state, and defensively checks the instance as well. Appreciate the feedback from you both!

**Comment by garylee1** [comment]
@edenman @falcon4ever We have a PR out that addresses this and also respects any calls made to `setUserId` and `unsetUserId` that occur before Sift has been opened:

https://github.com/SiftScience/sift-android/pull/51

**Comment by edenman** [comment]
This looks great, thanks @garylee1!

**Comment by garylee1** [comment]
We've fixed this with https://github.com/SiftScience/sift-android/releases/tag/v0.10.2-beta !
