### ISSUE TITLE
Custom Events

### ISSUE THREAD

**Issue by brunogabriel** [SiftScience/sift-android#6]
Hi, in Sift-java implementation I've possibility to add custom fields, but in this library I didn't found anything. iOs implementation has SFEvent, but in Android not, there's anything like that ?  

Thank you

**Comment by garylee1** [comment]
@brunogabriel – custom events do not apply to our iOS and Android SDKs and will be discarded if sent (they exist in iOS only as a relic of a very early beta period and we will remove them soon). 

Our Sift Java SDK is a client on top of our [REST Events API](https://siftscience.com/developers/docs/curl/events-api), which supports custom events, whereas our mobile SDKs perform automated tracking (analogous to our [JavaScript snippet](https://siftscience.com/developers/docs/javascript/javascript-api)) and there is no notion of a custom event because these are SDK-constructed events centered around device information and page tracking. So you would probably implement any custom event tracking server-side along with the rest of your event tracking rather than in your application.

Let me know if this makes sense – happy to answer any questions you have around this.
