### ISSUE TITLE
Build error when using siftscience 0.10.4

### ISSUE THREAD

**Issue by danielhermawan** [SiftScience/sift-android#64]
Got this error when try to build project after update from 0.10.3-beta to 0.10.4

```
error: package org.apache.commons.lang3 does not exist
import org.apache.commons.lang3.ArrayUtils;
```

Somehow package from library apache-common is not detected or found when i try to build after i update the siftscience.

**Comment by ehrmann** [comment]
Do you have something stale in your project directory? We removed commons-lang as a requirement in d61f326, and I can't find `ArrayUtils` or anything related to commons-lang when I search the repo.

**Comment by danielhermawan** [comment]
We are using common-lang as dependency in our project. Somehow reference to all class from package common-lang such as arrayutils and stringUtil that we use in our project isn't detected when we try to build it after updating the siftscience, even thought we haven't remove the dependency of apache common-lang

**Comment by quanpod** [comment]
One other thing - please update to latest, 0.10.4 has been a particularly
troublesome version.

**Comment by ehrmann** [comment]
Any chance you have `commons-lang` 2.x as a dependency? `commons-lang` changed package names from `org.apache.commons.lang` to `org.apache.commons.lang3` between 2.x and 3.x. If you included 2.x as a dependency, but accidentally imported a class from 3.x (both have `ArrayUtils` implementations) because it was previously available as a transitive dependence through `sift-android`, upgrading `sift-android` would break your build in this way.

If this is the case, the fix is either change the import from `org.apache.commons.lang3.ArrayUtils` to `org.apache.commons.lang.ArrayUtils` (verifying the behavior between versions is the same) or adding `commons-lang3` to gradle:

```
compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.8.1'
```

**Comment by danielhermawan** [comment]
@ehrmann We are using common-lang 3.x and using package from org.apache.commons.lang3. But somehow after i update to siftsciend to 0.10.4, that package isn't detected when i am try to compile

**Comment by ehrmann** [comment]
Is the dependency tagged as a test dependency?

I'm running out of ideas. We have nothing in the project related to commons-lang anymore. I created a new project in Android Studio, added sift-android 0.10.4 and commons-lang3 3.8.1 as dependencies, and Android Studio allowed me to import classes from both without any issues.

**Comment by danielhermawan** [comment]
I find the fix. It seem our module that use siftscience forgot to add apache library as dependency in gradle, so we were using apache package from siftscience before siftscience removing apache dependency in the new version. Sorry for the trouble.
